name: wp-plugin-release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get Repository Name
        run: |
          echo "PLUGIN_NAME=$(basename $GITHUB_REPOSITORY)" >> $GITHUB_ENV
          echo "$(basename $GITHUB_REPOSITORY)" > plugin_name.txt
      - name: Save Plugin Name
        uses: actions/upload-artifact@v4
        with:
          name: plugin_name
          path: plugin_name.txt
      - name: Create Plugin Zip
        run: |
          mkdir $PLUGIN_NAME
          rsync -av --progress ./ ./$PLUGIN_NAME/ --exclude=$PLUGIN_NAME
          zip -r $PLUGIN_NAME.zip $PLUGIN_NAME/
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: plugin-zip
          path: ${{ env.PLUGIN_NAME }}.zip
  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Download Plugin Name
        uses: actions/download-artifact@v4
        with:
          name: plugin_name
          path: ./
      - name: Load Plugin Name
        run: echo "PLUGIN_NAME=$(cat plugin_name.txt)" >> $GITHUB_ENV
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: plugin-zip
          path: ./
      - name: List Files
        run: ls -R
      - name: Generate Changelog
        run: echo "Release Notes for ${{ github.ref_name }}" > release-notes.md

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref_name }}
          body_path: release-notes.md
          files: ${{ env.PLUGIN_NAME }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
